# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46751fab5001b77c91c3b3fab7676502bc0ce78f55d9db8791e841ada1021f6efc8035b3e86e7ab74dbd4d3ace519723e67b8812bb9a72f0d47c3b705499e16e

test:
  secret_key_base: f26701ea0b5e3c16ff41d8a87f1821e9c101765c37f2adcb428c174e8f727d6f93274faadfd75d07a8a580810e14546d46962ed5e381a712c2e6d100da89e180

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
